name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install gcc
        pip install wheel pylint
        pip install octoprint
        pip install .

    - name: PyLint Errors
      run: |
        export PATH=$HOME/.local/bin:$PATH
        pylint --disable=R,C,W **/*.py
